const mongoose=require('mongoose')
const {User}= require('./user')

const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        phoneNum:{
            type:String,
            required:true
        },
        town:{
            type:String,
            required:true
        },
    },
    user:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            quantity:{
                type:Number,
                required:true,
                default:1
            },
            price:{
                type:Number,
                required:true
            },
            product:{
                type:mongoose.Schema.Types.ObjectId,
                required:true,
                ref:'Product'
            },
        }
    ],
    paymentInfo:{
        id:{
            type:String
        },
        status:{
            type:String
        }
    },
    payedAt:{
        type:Date,
    },
    itemsPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    totalPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    orderStatus:{
        type:String,
        default:'pending'
    },
    deliveredAt:{
        type:Date,
    },

},{
    timestamps:true
})

module.exports=mongoose.model('Order',orderSchema);